### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by R2mzi** [yash1441/Chat-Valorant-Rank#10]
Hey, 

Recently started using this and it was working perfectly. Now it is giving me Error 400 whenever I use it. 

Region: eu
Name: Polaris
Tag:  D22 

Thanks,

**Comment by yash1441** [comment]
Hey, if it was working earlier and giving an error just now then that means it is due to some issues on the backend API I used (The one mentioned in the Readme). 
As for the solution, there is nothing me or you can do except wait for them to fix the issues (Riot auth issues I presume) on their end. It'll hopefully be resolved within a few hours at best. Sorry for the inconvenience!

**Comment by R2mzi** [comment]
Thank you for reply. I thought there is something wrong because I looked to the API Service and it was online at that moment. However, I can see it as down now so it make sense, Thank you again, appreciated.
