### ISSUE TITLE
Server not responding

### ISSUE THREAD

**Issue by Depotys** [yash1441/Chat-Valorant-Rank#4]
Hey. Hey,

the endpoint stopped working for a lot of people. Glitch started using cloudflare to block machine requests. Could something be done about this please?

**Comment by yash1441** [comment]
Hey, I just tested it out and it seems to work.
There is one thing to note though. If no one used the endpoint for 5 minutes or more then the first call to it would take a little long and give you an error but any subsequent calls would be instant for the next 5 minutes as the server has awoken due to the first (errored) call.

![image](https://github.com/yash1441/Chat-Valorant-Rank/assets/14055917/67e6fe84-611e-43fd-8da7-ae8d08d9cb10)
