### ISSUE TITLE
customapi variable

### ISSUE THREAD

**Issue by LukeInCode** [yash1441/Chat-Valorant-Rank#6]
Hi everyone,

Before I ask everything I want to define that I'm not an expert developer, I can see that there's a variable named customapi in the link.  
Can you please tell me what should I replace with that?

Thanks

**Comment by yash1441** [comment]
If you can tell me where exactly you are trying to use this rank command, I can help you further

**Comment by LukeInCode** [comment]
I would like to do a fetch with js on it. I can post a snippet for give a more accurated idea.

**Comment by yash1441** [comment]
In that case you should probably look into [this API](https://app.swaggerhub.com/apis-docs/Henrik-3/HenrikDev-API/) instead of mine because the one I made is specifically catered towards streaming bots like StreamElements, Nightbot, etc.
Send a GET request to `https://api.henrikdev.xyz/valorant/v2/mmr/<region>/<name>/<tag>` after replacing the 3 variables.

**Comment by LukeInCode** [comment]
Oh, thanks. Just one question, how people use this api so?

**Comment by LukeInCode** [comment]
Thanks so much
